const types = {
  // layouts
  TOGGLE_SIDE_BAR: 'TOGGLE_SIDE_BAR',
  // assignments
  ADD_CLIENT_ORDER: 'ADD_CLIENT_ORDER',
  ADD_SERVICE_ORDER: 'ADD_SERVICE_ORDER',
  CHANGE_AMOUNT_SERVICE: 'CHANGE_AMOUNT_SERVICE',
  ADD_EMPLOYEE_ORDER: 'ADD_EMPLOYEE_ORDER',
  RESET_DATA_TO_ORDER: 'RESET_DATA_TO_ORDER',
};

export default types;
